package jogo;

import java.rmi.RemoteException;
import java.util.ArrayList;

public final class PanelJogador extends javax.swing.JPanel {

    protected JogadorInterface player;
    private CardLabel cardLabel;

    public PanelJogador(JogadorInterface player) {
        initComponents();
        this.player = player;

    }

    public void loadFromPlayer(JogadorInterface p) {
        panelJog1.removeAll();
        this.player = p;
        

        try {
            if (player == null) {
                nomeJog.setText("Vazio");
            } else {
                nomeJog.setText(player.getUsername() + ": €" + player.getQuantia());
                if (player.isStarted()) {
                    valor.setText("Aposta: " + player.getMao(0).getAposta());
                } else {
                    valor.setText("");
                }

                setTextContent(player.getMao(0));

            }
        } catch (RemoteException e) {
            e.printStackTrace();
        }
    }

    public void setTextContent(MaoInterface hand) throws RemoteException {
        String content = "";
        int local = 20;
        if (hand != null) {
            ArrayList<int[]> list = hand.getCardsIntArray();

            for (int i = 0; i < list.size(); i++) {
                drawBlackjackJog(intArrayToString(list.get(i)), local);
                local += 60;
                for (int k = 0; k < player.getMaos().size(); k++) {
                    valor.setText(String.valueOf(player.getMaos().get(k).getPontos()));
                }

            }
        }
    }

    public void drawBlackjackJog(String c1, int location) {
        cardLabel = new CardLabel();
        cardLabel.setCardImage(c1);
        cardLabel.setCardCovered(false);
        cardLabel.setLocation(location, 20);
        this.panelJog1.add(cardLabel);
        repaint();
    }

    public static String intArrayToString(int[] array) {
        if (array[0] == -1 && array[1] == -1) {
            return "bv";
        } else {
            String suitString;
            switch (array[0]) {
                case 1:
                    suitString = "h";
                    break;
                case 2:
                    suitString = "d";
                    break;
                case 3:
                    suitString = "c";
                    break;
                default:
                    suitString = "s";
            }

            String valueString;
            switch (array[1]) {
                case 0:
                    valueString = "";
                case 1:
                    valueString = "1";
                    break;
                case 11:
                    valueString = "j";
                    break;
                case 12:
                    valueString = "q";
                    break;
                case 13:
                    valueString = "k";
                    break;
                default:
                    valueString = array[1] + "";
            }
            return suitString + "" + valueString;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeJog = new javax.swing.JLabel();
        valor = new javax.swing.JLabel();
        panelJog1 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(0, 153, 0));

        nomeJog.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nomeJog.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomeJog.setText("Jogador");

        valor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        valor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        valor.setText("pontos");

        panelJog1.setBackground(new java.awt.Color(0, 153, 0));

        javax.swing.GroupLayout panelJog1Layout = new javax.swing.GroupLayout(panelJog1);
        panelJog1.setLayout(panelJog1Layout);
        panelJog1Layout.setHorizontalGroup(
            panelJog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelJog1Layout.setVerticalGroup(
            panelJog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nomeJog, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelJog1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(valor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nomeJog)
                .addGap(29, 29, 29)
                .addComponent(panelJog1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(valor)
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel nomeJog;
    private javax.swing.JPanel panelJog1;
    private javax.swing.JLabel valor;
    // End of variables declaration//GEN-END:variables
}
